export const MockData = [
  {
    id: "9392",
    nutrition: {
      "@type": "NutritionInformation",
      calories: "288 kcal",
      carbohydrateContent: "24 g",
      proteinContent: "4 g",
      fatContent: "19 g",
      saturatedFatContent: "7 g",
      cholesterolContent: "43 mg",
      sodiumContent: "154 mg",
      fiberContent: "1 g",
      sugarContent: "9 g",
      servingSize: "1 serving",
    },
    ingredients: [
      "6 ounces cream cheese, at room temp",
      "2 Tablespoons sugar",
      "2 teaspoons lemon juice",
      "1 teaspoon lemon zest",
      "1 teaspoon vanilla extract",
      "1  (17.3-oz.) package frozen puff pastry (2 sheets), thawed",
      "1 1/2 cups fruit (See Kelly’s Note)",
      "1  large egg",
      "Sanding sugar (optional)",
    ],
    instructions: [
      "Preheat the oven to 400°F and line two baking sheets with parchment paper or Silpats.",
      "In the bowl of a stand mixer fitted with the paddle attachment, beat the cream cheese with the sugar, lemon juice, lemon zest and vanilla extract until creamy.",
      "Unfold the puff pastry sheets onto a lightly floured work surface. Lightly roll the pastry with a rolling pin to seal the perforations. Using a 4-inch round cookie cutter (or glass), cut out four circles from each sheet of puff pastry.",
      "Transfer four pastry circles onto each baking sheet, spacing the circles about 2 inches apart. Lightly score a circular border 1/4-inch from the edges then prick the centers of each pastry with a fork. Spread a portion of the cream cheese mixture inside the border of each pastry then top the cream cheese with fruit.",
      "In a small bowl, whisk together the egg with 1 tablespoon water. Brush the edges of the pastries with the egg wash then sprinkle them with the sanding sugar (optional). Bake the pastries for 15 to 18 minutes or until they’re golden and puffed.",
      "Remove the pastries from the oven and allow them to cool for 5 minutes on the baking sheets before transferring them to a cooling rack to cool completely.",
    ],
    times: {
      cook: "PT18M",
      prep: "PT10M",
      total: "PT28M",
    },
    images: [
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x500.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x375.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-480x270.jpg",
    ],
    name: "Fruit and Cream Cheese Breakfast Pastries test 1",
    description:
      "Up your brunch game with this fast and fresh recipe for Fruit and Cream Cheese Breakfast Pastries topped with your choice of fruit.",
    servings: ["8", "8 pastries"],
  },
  {
    id: "8302083",
    nutrition: {
      "@type": "NutritionInformation",
      calories: "288 kcal",
      carbohydrateContent: "24 g",
      proteinContent: "4 g",
      fatContent: "19 g",
      saturatedFatContent: "7 g",
      cholesterolContent: "43 mg",
      sodiumContent: "154 mg",
      fiberContent: "1 g",
      sugarContent: "9 g",
      servingSize: "1 serving",
    },
    ingredients: [
      "6 ounces cream cheese, at room temp",
      "2 Tablespoons sugar",
      "2 teaspoons lemon juice",
      "1 teaspoon lemon zest",
      "1 teaspoon vanilla extract",
      "1  (17.3-oz.) package frozen puff pastry (2 sheets), thawed",
      "1 1/2 cups fruit (See Kelly’s Note)",
      "1  large egg",
      "Sanding sugar (optional)",
    ],
    instructions: [
      "Preheat the oven to 400°F and line two baking sheets with parchment paper or Silpats.",
      "In the bowl of a stand mixer fitted with the paddle attachment, beat the cream cheese with the sugar, lemon juice, lemon zest and vanilla extract until creamy.",
      "Unfold the puff pastry sheets onto a lightly floured work surface. Lightly roll the pastry with a rolling pin to seal the perforations. Using a 4-inch round cookie cutter (or glass), cut out four circles from each sheet of puff pastry.",
      "Transfer four pastry circles onto each baking sheet, spacing the circles about 2 inches apart. Lightly score a circular border 1/4-inch from the edges then prick the centers of each pastry with a fork. Spread a portion of the cream cheese mixture inside the border of each pastry then top the cream cheese with fruit.",
      "In a small bowl, whisk together the egg with 1 tablespoon water. Brush the edges of the pastries with the egg wash then sprinkle them with the sanding sugar (optional). Bake the pastries for 15 to 18 minutes or until they’re golden and puffed.",
      "Remove the pastries from the oven and allow them to cool for 5 minutes on the baking sheets before transferring them to a cooling rack to cool completely.",
    ],
    times: {
      cook: "PT18M",
      prep: "PT10M",
      total: "PT28M",
    },
    images: [
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x500.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x375.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-480x270.jpg",
    ],
    name: "Fruit and Cream Cheese Breakfast Pastries test 2",
    description:
      "Up your brunch game with this fast and fresh recipe for Fruit and Cream Cheese Breakfast Pastries topped with your choice of fruit.",
    servings: ["8", "8 pastries"],
  },
  {
    id: "843ddk0",
    nutrition: {
      "@type": "NutritionInformation",
      calories: "288 kcal",
      carbohydrateContent: "24 g",
      proteinContent: "4 g",
      fatContent: "19 g",
      saturatedFatContent: "7 g",
      cholesterolContent: "43 mg",
      sodiumContent: "154 mg",
      fiberContent: "1 g",
      sugarContent: "9 g",
      servingSize: "1 serving",
    },
    ingredients: [
      "6 ounces cream cheese, at room temp",
      "2 Tablespoons sugar",
      "2 teaspoons lemon juice",
      "1 teaspoon lemon zest",
      "1 teaspoon vanilla extract",
      "1  (17.3-oz.) package frozen puff pastry (2 sheets), thawed",
      "1 1/2 cups fruit (See Kelly’s Note)",
      "1  large egg",
      "Sanding sugar (optional)",
    ],
    instructions: [
      "Preheat the oven to 400°F and line two baking sheets with parchment paper or Silpats.",
      "In the bowl of a stand mixer fitted with the paddle attachment, beat the cream cheese with the sugar, lemon juice, lemon zest and vanilla extract until creamy.",
      "Unfold the puff pastry sheets onto a lightly floured work surface. Lightly roll the pastry with a rolling pin to seal the perforations. Using a 4-inch round cookie cutter (or glass), cut out four circles from each sheet of puff pastry.",
      "Transfer four pastry circles onto each baking sheet, spacing the circles about 2 inches apart. Lightly score a circular border 1/4-inch from the edges then prick the centers of each pastry with a fork. Spread a portion of the cream cheese mixture inside the border of each pastry then top the cream cheese with fruit.",
      "In a small bowl, whisk together the egg with 1 tablespoon water. Brush the edges of the pastries with the egg wash then sprinkle them with the sanding sugar (optional). Bake the pastries for 15 to 18 minutes or until they’re golden and puffed.",
      "Remove the pastries from the oven and allow them to cool for 5 minutes on the baking sheets before transferring them to a cooling rack to cool completely.",
    ],
    times: {
      cook: "PT18M",
      prep: "PT10M",
      total: "PT28M",
    },
    images: [
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x500.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x375.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-480x270.jpg",
    ],
    name: "Fruit and Cream Cheese Breakfast Pastries test 3",
    description:
      "Up your brunch game with this fast and fresh recipe for Fruit and Cream Cheese Breakfast Pastries topped with your choice of fruit.",
    servings: ["8", "8 pastries"],
  },
  {
    id: "9d9fjs934",
    nutrition: {
      "@type": "NutritionInformation",
      calories: "288 kcal",
      carbohydrateContent: "24 g",
      proteinContent: "4 g",
      fatContent: "19 g",
      saturatedFatContent: "7 g",
      cholesterolContent: "43 mg",
      sodiumContent: "154 mg",
      fiberContent: "1 g",
      sugarContent: "9 g",
      servingSize: "1 serving",
    },
    ingredients: [
      "6 ounces cream cheese, at room temp",
      "2 Tablespoons sugar",
      "2 teaspoons lemon juice",
      "1 teaspoon lemon zest",
      "1 teaspoon vanilla extract",
      "1  (17.3-oz.) package frozen puff pastry (2 sheets), thawed",
      "1 1/2 cups fruit (See Kelly’s Note)",
      "1  large egg",
      "Sanding sugar (optional)",
    ],
    instructions: [
      "Preheat the oven to 400°F and line two baking sheets with parchment paper or Silpats.",
      "In the bowl of a stand mixer fitted with the paddle attachment, beat the cream cheese with the sugar, lemon juice, lemon zest and vanilla extract until creamy.",
      "Unfold the puff pastry sheets onto a lightly floured work surface. Lightly roll the pastry with a rolling pin to seal the perforations. Using a 4-inch round cookie cutter (or glass), cut out four circles from each sheet of puff pastry.",
      "Transfer four pastry circles onto each baking sheet, spacing the circles about 2 inches apart. Lightly score a circular border 1/4-inch from the edges then prick the centers of each pastry with a fork. Spread a portion of the cream cheese mixture inside the border of each pastry then top the cream cheese with fruit.",
      "In a small bowl, whisk together the egg with 1 tablespoon water. Brush the edges of the pastries with the egg wash then sprinkle them with the sanding sugar (optional). Bake the pastries for 15 to 18 minutes or until they’re golden and puffed.",
      "Remove the pastries from the oven and allow them to cool for 5 minutes on the baking sheets before transferring them to a cooling rack to cool completely.",
    ],
    times: {
      cook: "PT18M",
      prep: "PT10M",
      total: "PT28M",
    },
    images: [
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x500.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x375.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-480x270.jpg",
    ],
    name: "Fruit and Cream Cheese Breakfast Pastries test 4",
    description:
      "Up your brunch game with this fast and fresh recipe for Fruit and Cream Cheese Breakfast Pastries topped with your choice of fruit.",
    servings: ["8", "8 pastries"],
  },
  {
    id: "f9394384",
    nutrition: {
      "@type": "NutritionInformation",
      calories: "288 kcal",
      carbohydrateContent: "24 g",
      proteinContent: "4 g",
      fatContent: "19 g",
      saturatedFatContent: "7 g",
      cholesterolContent: "43 mg",
      sodiumContent: "154 mg",
      fiberContent: "1 g",
      sugarContent: "9 g",
      servingSize: "1 serving",
    },
    ingredients: [
      "6 ounces cream cheese, at room temp",
      "2 Tablespoons sugar",
      "2 teaspoons lemon juice",
      "1 teaspoon lemon zest",
      "1 teaspoon vanilla extract",
      "1  (17.3-oz.) package frozen puff pastry (2 sheets), thawed",
      "1 1/2 cups fruit (See Kelly’s Note)",
      "1  large egg",
      "Sanding sugar (optional)",
    ],
    instructions: [
      "Preheat the oven to 400°F and line two baking sheets with parchment paper or Silpats.",
      "In the bowl of a stand mixer fitted with the paddle attachment, beat the cream cheese with the sugar, lemon juice, lemon zest and vanilla extract until creamy.",
      "Unfold the puff pastry sheets onto a lightly floured work surface. Lightly roll the pastry with a rolling pin to seal the perforations. Using a 4-inch round cookie cutter (or glass), cut out four circles from each sheet of puff pastry.",
      "Transfer four pastry circles onto each baking sheet, spacing the circles about 2 inches apart. Lightly score a circular border 1/4-inch from the edges then prick the centers of each pastry with a fork. Spread a portion of the cream cheese mixture inside the border of each pastry then top the cream cheese with fruit.",
      "In a small bowl, whisk together the egg with 1 tablespoon water. Brush the edges of the pastries with the egg wash then sprinkle them with the sanding sugar (optional). Bake the pastries for 15 to 18 minutes or until they’re golden and puffed.",
      "Remove the pastries from the oven and allow them to cool for 5 minutes on the baking sheets before transferring them to a cooling rack to cool completely.",
    ],
    times: {
      cook: "PT18M",
      prep: "PT10M",
      total: "PT28M",
    },
    images: [
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x500.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x375.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-480x270.jpg",
    ],
    name: "Fruit and Cream Cheese Breakfast Pastries test 5",
    description:
      "Up your brunch game with this fast and fresh recipe for Fruit and Cream Cheese Breakfast Pastries topped with your choice of fruit.",
    servings: ["8", "8 pastries"],
  },
  {
    id: "039483928",
    nutrition: {
      "@type": "NutritionInformation",
      calories: "288 kcal",
      carbohydrateContent: "24 g",
      proteinContent: "4 g",
      fatContent: "19 g",
      saturatedFatContent: "7 g",
      cholesterolContent: "43 mg",
      sodiumContent: "154 mg",
      fiberContent: "1 g",
      sugarContent: "9 g",
      servingSize: "1 serving",
    },
    ingredients: [
      "6 ounces cream cheese, at room temp",
      "2 Tablespoons sugar",
      "2 teaspoons lemon juice",
      "1 teaspoon lemon zest",
      "1 teaspoon vanilla extract",
      "1  (17.3-oz.) package frozen puff pastry (2 sheets), thawed",
      "1 1/2 cups fruit (See Kelly’s Note)",
      "1  large egg",
      "Sanding sugar (optional)",
    ],
    instructions: [
      "Preheat the oven to 400°F and line two baking sheets with parchment paper or Silpats.",
      "In the bowl of a stand mixer fitted with the paddle attachment, beat the cream cheese with the sugar, lemon juice, lemon zest and vanilla extract until creamy.",
      "Unfold the puff pastry sheets onto a lightly floured work surface. Lightly roll the pastry with a rolling pin to seal the perforations. Using a 4-inch round cookie cutter (or glass), cut out four circles from each sheet of puff pastry.",
      "Transfer four pastry circles onto each baking sheet, spacing the circles about 2 inches apart. Lightly score a circular border 1/4-inch from the edges then prick the centers of each pastry with a fork. Spread a portion of the cream cheese mixture inside the border of each pastry then top the cream cheese with fruit.",
      "In a small bowl, whisk together the egg with 1 tablespoon water. Brush the edges of the pastries with the egg wash then sprinkle them with the sanding sugar (optional). Bake the pastries for 15 to 18 minutes or until they’re golden and puffed.",
      "Remove the pastries from the oven and allow them to cool for 5 minutes on the baking sheets before transferring them to a cooling rack to cool completely.",
    ],
    times: {
      cook: "PT18M",
      prep: "PT10M",
      total: "PT28M",
    },
    images: [
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x500.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x375.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-480x270.jpg",
    ],
    name: "Fruit and Cream Cheese Breakfast Pastries test 6",
    description:
      "Up your brunch game with this fast and fresh recipe for Fruit and Cream Cheese Breakfast Pastries topped with your choice of fruit.",
    servings: ["8", "8 pastries"],
  },
  {
    id: "fj984923899",
    nutrition: {
      "@type": "NutritionInformation",
      calories: "288 kcal",
      carbohydrateContent: "24 g",
      proteinContent: "4 g",
      fatContent: "19 g",
      saturatedFatContent: "7 g",
      cholesterolContent: "43 mg",
      sodiumContent: "154 mg",
      fiberContent: "1 g",
      sugarContent: "9 g",
      servingSize: "1 serving",
    },
    ingredients: [
      "6 ounces cream cheese, at room temp",
      "2 Tablespoons sugar",
      "2 teaspoons lemon juice",
      "1 teaspoon lemon zest",
      "1 teaspoon vanilla extract",
      "1  (17.3-oz.) package frozen puff pastry (2 sheets), thawed",
      "1 1/2 cups fruit (See Kelly’s Note)",
      "1  large egg",
      "Sanding sugar (optional)",
    ],
    instructions: [
      "Preheat the oven to 400°F and line two baking sheets with parchment paper or Silpats.",
      "In the bowl of a stand mixer fitted with the paddle attachment, beat the cream cheese with the sugar, lemon juice, lemon zest and vanilla extract until creamy.",
      "Unfold the puff pastry sheets onto a lightly floured work surface. Lightly roll the pastry with a rolling pin to seal the perforations. Using a 4-inch round cookie cutter (or glass), cut out four circles from each sheet of puff pastry.",
      "Transfer four pastry circles onto each baking sheet, spacing the circles about 2 inches apart. Lightly score a circular border 1/4-inch from the edges then prick the centers of each pastry with a fork. Spread a portion of the cream cheese mixture inside the border of each pastry then top the cream cheese with fruit.",
      "In a small bowl, whisk together the egg with 1 tablespoon water. Brush the edges of the pastries with the egg wash then sprinkle them with the sanding sugar (optional). Bake the pastries for 15 to 18 minutes or until they’re golden and puffed.",
      "Remove the pastries from the oven and allow them to cool for 5 minutes on the baking sheets before transferring them to a cooling rack to cool completely.",
    ],
    times: {
      cook: "PT18M",
      prep: "PT10M",
      total: "PT28M",
    },
    images: [
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x500.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x375.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-480x270.jpg",
    ],
    name: "Fruit and Cream Cheese Breakfast Pastries test 7",
    description:
      "Up your brunch game with this fast and fresh recipe for Fruit and Cream Cheese Breakfast Pastries topped with your choice of fruit.",
    servings: ["8", "8 pastries"],
  },
  {
    id: "887473",
    nutrition: {
      "@type": "NutritionInformation",
      calories: "288 kcal",
      carbohydrateContent: "24 g",
      proteinContent: "4 g",
      fatContent: "19 g",
      saturatedFatContent: "7 g",
      cholesterolContent: "43 mg",
      sodiumContent: "154 mg",
      fiberContent: "1 g",
      sugarContent: "9 g",
      servingSize: "1 serving",
    },
    ingredients: [
      "6 ounces cream cheese, at room temp",
      "2 Tablespoons sugar",
      "2 teaspoons lemon juice",
      "1 teaspoon lemon zest",
      "1 teaspoon vanilla extract",
      "1  (17.3-oz.) package frozen puff pastry (2 sheets), thawed",
      "1 1/2 cups fruit (See Kelly’s Note)",
      "1  large egg",
      "Sanding sugar (optional)",
    ],
    instructions: [
      "Preheat the oven to 400°F and line two baking sheets with parchment paper or Silpats.",
      "In the bowl of a stand mixer fitted with the paddle attachment, beat the cream cheese with the sugar, lemon juice, lemon zest and vanilla extract until creamy.",
      "Unfold the puff pastry sheets onto a lightly floured work surface. Lightly roll the pastry with a rolling pin to seal the perforations. Using a 4-inch round cookie cutter (or glass), cut out four circles from each sheet of puff pastry.",
      "Transfer four pastry circles onto each baking sheet, spacing the circles about 2 inches apart. Lightly score a circular border 1/4-inch from the edges then prick the centers of each pastry with a fork. Spread a portion of the cream cheese mixture inside the border of each pastry then top the cream cheese with fruit.",
      "In a small bowl, whisk together the egg with 1 tablespoon water. Brush the edges of the pastries with the egg wash then sprinkle them with the sanding sugar (optional). Bake the pastries for 15 to 18 minutes or until they’re golden and puffed.",
      "Remove the pastries from the oven and allow them to cool for 5 minutes on the baking sheets before transferring them to a cooling rack to cool completely.",
    ],
    times: {
      cook: "PT18M",
      prep: "PT10M",
      total: "PT28M",
    },
    images: [
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x500.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x375.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-480x270.jpg",
    ],
    name: "Fruit and Cream Cheese Breakfast Pastries test 8",
    description:
      "Up your brunch game with this fast and fresh recipe for Fruit and Cream Cheese Breakfast Pastries topped with your choice of fruit.",
    servings: ["8", "8 pastries"],
  },
  {
    id: "0023838",
    nutrition: {
      "@type": "NutritionInformation",
      calories: "288 kcal",
      carbohydrateContent: "24 g",
      proteinContent: "4 g",
      fatContent: "19 g",
      saturatedFatContent: "7 g",
      cholesterolContent: "43 mg",
      sodiumContent: "154 mg",
      fiberContent: "1 g",
      sugarContent: "9 g",
      servingSize: "1 serving",
    },
    ingredients: [
      "6 ounces cream cheese, at room temp",
      "2 Tablespoons sugar",
      "2 teaspoons lemon juice",
      "1 teaspoon lemon zest",
      "1 teaspoon vanilla extract",
      "1  (17.3-oz.) package frozen puff pastry (2 sheets), thawed",
      "1 1/2 cups fruit (See Kelly’s Note)",
      "1  large egg",
      "Sanding sugar (optional)",
    ],
    instructions: [
      "Preheat the oven to 400°F and line two baking sheets with parchment paper or Silpats.",
      "In the bowl of a stand mixer fitted with the paddle attachment, beat the cream cheese with the sugar, lemon juice, lemon zest and vanilla extract until creamy.",
      "Unfold the puff pastry sheets onto a lightly floured work surface. Lightly roll the pastry with a rolling pin to seal the perforations. Using a 4-inch round cookie cutter (or glass), cut out four circles from each sheet of puff pastry.",
      "Transfer four pastry circles onto each baking sheet, spacing the circles about 2 inches apart. Lightly score a circular border 1/4-inch from the edges then prick the centers of each pastry with a fork. Spread a portion of the cream cheese mixture inside the border of each pastry then top the cream cheese with fruit.",
      "In a small bowl, whisk together the egg with 1 tablespoon water. Brush the edges of the pastries with the egg wash then sprinkle them with the sanding sugar (optional). Bake the pastries for 15 to 18 minutes or until they’re golden and puffed.",
      "Remove the pastries from the oven and allow them to cool for 5 minutes on the baking sheets before transferring them to a cooling rack to cool completely.",
    ],
    times: {
      cook: "PT18M",
      prep: "PT10M",
      total: "PT28M",
    },
    images: [
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x500.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x375.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-480x270.jpg",
    ],
    name: "Fruit and Cream Cheese Breakfast Pastries test 9",
    description:
      "Up your brunch game with this fast and fresh recipe for Fruit and Cream Cheese Breakfast Pastries topped with your choice of fruit.",
    servings: ["8", "8 pastries"],
  },
  {
    id: "12382980",
    nutrition: {
      "@type": "NutritionInformation",
      calories: "288 kcal",
      carbohydrateContent: "24 g",
      proteinContent: "4 g",
      fatContent: "19 g",
      saturatedFatContent: "7 g",
      cholesterolContent: "43 mg",
      sodiumContent: "154 mg",
      fiberContent: "1 g",
      sugarContent: "9 g",
      servingSize: "1 serving",
    },
    ingredients: [
      "6 ounces cream cheese, at room temp",
      "2 Tablespoons sugar",
      "2 teaspoons lemon juice",
      "1 teaspoon lemon zest",
      "1 teaspoon vanilla extract",
      "1  (17.3-oz.) package frozen puff pastry (2 sheets), thawed",
      "1 1/2 cups fruit (See Kelly’s Note)",
      "1  large egg",
      "Sanding sugar (optional)",
    ],
    instructions: [
      "Preheat the oven to 400°F and line two baking sheets with parchment paper or Silpats.",
      "In the bowl of a stand mixer fitted with the paddle attachment, beat the cream cheese with the sugar, lemon juice, lemon zest and vanilla extract until creamy.",
      "Unfold the puff pastry sheets onto a lightly floured work surface. Lightly roll the pastry with a rolling pin to seal the perforations. Using a 4-inch round cookie cutter (or glass), cut out four circles from each sheet of puff pastry.",
      "Transfer four pastry circles onto each baking sheet, spacing the circles about 2 inches apart. Lightly score a circular border 1/4-inch from the edges then prick the centers of each pastry with a fork. Spread a portion of the cream cheese mixture inside the border of each pastry then top the cream cheese with fruit.",
      "In a small bowl, whisk together the egg with 1 tablespoon water. Brush the edges of the pastries with the egg wash then sprinkle them with the sanding sugar (optional). Bake the pastries for 15 to 18 minutes or until they’re golden and puffed.",
      "Remove the pastries from the oven and allow them to cool for 5 minutes on the baking sheets before transferring them to a cooling rack to cool completely.",
    ],
    times: {
      cook: "PT18M",
      prep: "PT10M",
      total: "PT28M",
    },
    images: [
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x500.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-500x375.jpg",
      "https://www.justataste.com/wp-content/uploads/2016/03/cream-cheese-pastries-fruit-480x270.jpg",
    ],
    name: "Fruit and Cream Cheese Breakfast Pastries test 10",
    description:
      "Up your brunch game with this fast and fresh recipe for Fruit and Cream Cheese Breakfast Pastries topped with your choice of fruit.",
    servings: ["8", "8 pastries"],
  },
];
